In [9]:
import tensorflow as tf
from tensorflow import keras

import tensorflow_datasets as tfds

In [21]:
model = keras.models.load_model('/Users/land/Documents/Workspace/ML/tf/OmegaTensor/Tensorflow_official/RNN/text_classification/colab_4-13-10-11.h5')

加载数据集

In [22]:
dataset, info = tfds.load('imdb_reviews/subwords8k',
                          with_info=True,
                          as_supervised=True)
train_dataset, test_dataset = dataset['train'], dataset['test']

In [23]:
encoder = info.features['text'].encoder

预测

In [24]:
def pad_zero_to_size(vec, size):
    zeros = [0] * (size - len(vec))
    vec.extend(zeros)
    return vec

In [25]:
def sample_predict(text, is_pad):
    encoded_text = encoder.encode(text)

    if is_pad:
        encoded_text = pad_zero_to_size(encoded_text, 64)
    encoded_text = tf.cast(encoded_text, tf.float32)

    return model.predict(tf.expand_dims(encoded_text, 0))

In [26]:
sample_text = "The movie was cool."
predictions = sample_predict(sample_text, is_pad=True)
predictions

array([[0.16169925]], dtype=float32)

In [27]:
sample_text = "The movie was bad."
predictions = sample_predict(sample_text, is_pad=True)
predictions

array([[-1.3853544]], dtype=float32)

In [28]:
sample_text = "The movie was not bad."
predictions = sample_predict(sample_text, is_pad=True)
predictions

array([[-1.6652696]], dtype=float32)